version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis-db
    command: redis-server --requirepass "akitavis"
    volumes:
      - ./example/demo.rdb:/data/dump.rdb

  server:
    image: golang:alpine
    container_name: vis4mesh-backend
    links:
      - redis
    environment:
      - AKITA_TRACE_USERNAME=akita
      - AKITA_TRACE_PASSWORD=akitavis
      - AKITA_TRACE_IP=redis
      - AKITA_TRACE_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/vis4mesh
      - ./docker-entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - "8080:8080"
    restart: always
